name: "ðŸ¤– Renovate Dependencies"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * 0" # Every Sunday at 23:30 IST (18:00 UTC)

permissions:
  contents: write
  pull-requests: write

jobs:
  renovate:
    name: "ðŸ§¹ Scan & Update deps"
    runs-on: ubuntu-latest
    steps:
      - name: "ðŸ“¥ Checkout repository"
        uses: actions/checkout@v6

      - name: "ðŸ¤– Run Renovate bot"
        uses: renovatebot/github-action@v44.1.0
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
